### ISSUE TITLE
Fixing lint in local or Github Action?

### ISSUE THREAD

**Issue by dominosaurs** [apa-developer/apa-ui#46]
The #25 changes add an Action (https://github.com/apa-developer/apa-ui/pull/25/commits/baab16622d5f2afdd2a16c8f13069c1ba508d872) that will fix lint error(s) on pull request by the Action worker. However the #36 changes added scripts about lint that will run in local commit process. It seems redundant. What you guys preferred?

**Comment by powxenv** [comment]
The reason i have both local linting (via Husky) and GitHub Actions linting is to ensure a robust workflow:

- Local linting: Gives quick feedback during the commit process and helps **reduce back-and-forth** on pull requests by catching errors early.
- GitHub Actions linting: Acts as a safety net and ensures consistency across all pull requests, especially useful for contributors **who might bypass or misconfigure local linting**.

 However, if you or anyone in the community have concerns or suggestions, i'm open to discussing and improving the workflow

**Comment by powxenv** [comment]
I acknowledge that automatic lint:fix and commit in Actions might feel redundant. I suggest to adjusting Actions to validate linting without modifying the code.

**Comment by dominosaurs** [comment]
dear @kimmyxpow,

lah

best regards, zain🍕

**Comment by powxenv** [comment]
Auto fixing and committing changes in CI/CD can be confusing for contributors as it introduces unexpected changes to their PRs, slows down the review process due to additional commits, and blurs the responsibility of ensuring code quality between contributors and the CI pipeline. It's generally better to validate linting in CI without making automated fixes, leaving those adjustments to the contributor's local environment.

**Comment by dominosaurs** [comment]
dear @kimmyxpow,

y

best regards, zain🍕
